apiVersion: v1
data:
  sidecar.automountServiceAccountToken: "true"
  sidecar.container: |
    command:
    - argo-chaos-mesh-plugin
    - server
    image: ccr.ccs.tencentyun.com/xlgao/argo-chaos-mesh-plugin:v0.0.1
    name: chaos-mesh-executor-plugin
    ports:
    - containerPort: 8443
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 64Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  name: chaosmesh-executor-plugin
  namespace: argo