apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaosmesh-executor-plugin
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-chaos-mesh-plugin-role
  namespace: argo
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["chaos-mesh.org"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: argo
  annotations:
    workflows.argoproj.io/description: |
      Recommended minimum permissions for the `docker` executor.
      This executor is superseded by  the `emmisary` executor, so we do not recommend you use it anymore.
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-chaos-mesh-plugin-binding
subjects:
  - kind: ServiceAccount
    name: chaosmesh-executor-plugin
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-chaos-mesh-plugin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-role-bind
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: chaosmesh-executor-plugin
    namespace: argo
